import React from 'react';

export type AttributionType = 'AI Assisted' | 'Human' | 'Human Edited';

interface AttributionBadgeProps {
    type: AttributionType;
    className?: string;
    size?: 'xs' | 'sm';
}

const AttributionBadge: React.FC<AttributionBadgeProps> = ({ type, className = '', size = 'xs' }) => {
    const isAi = type === 'AI Assisted';
    const leftText = isAi ? "AI" : "Human";
    const rightText = isAi ? "Assisted" : "Edited";

    const rightBg = isAi ? "bg-[#7c007c]" : "bg-[#f17a35]"; // Using specific colors from image
    const leftBg = "bg-[#444444]";

    const containerSize = size === 'xs' ? "text-[8px]" : "text-[9px]";

    const tooltip = isAi
        ? "This content was initially generated by AI to give you a head start."
        : "You have refined or verified this content to ensure accuracy.";

    const fontClass = "font-sans font-bold uppercase leading-none";

    return (
        <div
            className={`inline-flex rounded overflow-hidden tracking-tight shadow-sm transition-transform hover:scale-105 mr-1.5 mb-1 ${containerSize} ${fontClass} ${className}`}
            title={tooltip}
        >
            <div className={`${leftBg} text-white px-1.5 py-[2px] flex items-center justify-center`}>
                {leftText}
            </div>
            <div className={`${rightBg} text-white px-1.5 py-[2px] flex items-center justify-center`}>
                {rightText}
            </div>
        </div>
    );
};

export default AttributionBadge;
