import { useMutation } from "convex/react";
import { api } from "../convex/_generated/api";

export const useUpdateProject = () => useMutation(api.projects.update);
export const useUpdateGoal = () => useMutation(api.goals.updateGoal);
export const useUpdateKeyResult = () => useMutation(api.goals.updateKeyResult);
export const useSyncKeyResult = () => useMutation(api.goals.syncKeyResult);
export const useUpdateRevenueStream = () => useMutation(api.revenue.updateRevenueStream);
export const useUpdateCost = () => useMutation(api.revenue.updateCost);
export const useUpdateDocument = () => useMutation(api.documents.updateDocument);
export const useUpdateFile = () => useMutation(api.files.updateFile);
export const useUpdateFolder = () => useMutation(api.files.updateFolder);
export const useMoveFile = () => useMutation(api.files.moveFile);
export const useMoveFolder = () => useMutation(api.files.moveFolder);
export const useUpdateBlogPost = () => useMutation(api.blog.updatePost);
export const useUpdateBlogCategory = () => useMutation(api.blog.updateCategory);
export const useUpdateFeature = () => useMutation(api.engineering.updateFeature);
export const useUpdateInitiative = () => useMutation(api.initiatives.updateInitiative);
export const useToggleInitiativeMember = () => useMutation(api.initiatives.toggleAssignMember);
export const useLinkFileToInitiative = () => useMutation(api.initiatives.linkFileToInitiative);
export const useUnlinkFileFromInitiative = () => useMutation(api.initiatives.unlinkFileFromInitiative);
export const useUpdateCanvasSection = () => useMutation(api.canvas.updateSection);
export const useUpdateMarket = () => useMutation(api.market.updateMarket);
export const useUpdateOnboardingStep = () => useMutation(api.users.updateOnboardingStep);
export const useCompleteOnboarding = () => useMutation(api.users.completeOnboarding);
export const useCompleteStory = () => useMutation(api.story.completeStory);
export const useSignDocument = () => useMutation(api.documents.signDocument);
export const useMarkNotificationRead = () => useMutation(api.notifications.markAsRead);
export const useUpdateChatTitle = () => useMutation(api.aiChat.updateChatTitle);
export const useSaveArchitectureNode = () => useMutation(api.engineering.saveArchitectureNode);
export const useUpdateManualCompetitor = () => useMutation(api.manual_competitors.updateManualCompetitor);
export const useUpdateIdeationWorkspace = () => useMutation(api.ideation.update);
export const useUpdateBusinessStructure = () => useMutation(api.team.updateBusinessStructure);
export const useUpdateOrganizationDetails = () => useMutation(api.team.updateOrganizationDetails);
export const useUpdateTeamMember = () => useMutation(api.team.updateMember);
export const useUpdateRole = () => useMutation(api.roles.update);
